// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A flow to enhance scene descriptions by reasoning about image details.
 *
 * - enhanceSceneDescription - A function that takes an image and object detections and returns an enhanced scene description.
 * - EnhanceSceneDescriptionInput - The input type for the enhanceSceneDescription function.
 * - EnhanceSceneDescriptionOutput - The return type for the enhanceSceneDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnhanceSceneDescriptionInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of the scene, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  detectedObjects: z.array(z.string()).describe('A list of detected objects in the scene.'),
  previousDescription: z.string().optional().describe('The previous scene description, if available.'),
});
export type EnhanceSceneDescriptionInput = z.infer<typeof EnhanceSceneDescriptionInputSchema>;

const EnhanceSceneDescriptionOutputSchema = z.object({
  enhancedDescription: z.string().describe('An enhanced, detailed description of the scene.'),
});
export type EnhanceSceneDescriptionOutput = z.infer<typeof EnhanceSceneDescriptionOutputSchema>;

export async function enhanceSceneDescription(input: EnhanceSceneDescriptionInput): Promise<EnhanceSceneDescriptionOutput> {
  return enhanceSceneDescriptionFlow(input);
}

const sceneEnhancementPrompt = ai.definePrompt({
  name: 'sceneEnhancementPrompt',
  input: {schema: EnhanceSceneDescriptionInputSchema},
  output: {schema: EnhanceSceneDescriptionOutputSchema},
  prompt: `You are an AI assistant that helps to improve scene descriptions based on detected objects in an image.

  Here is a base64 encoded data URI representing the photo:
  {{media url=photoDataUri}}

  Here are the objects detected in the scene:
  {{#each detectedObjects}}- {{this}}\n{{/each}}

  {{#if previousDescription}}
  Here is a previous description of the scene:
  {{previousDescription}}
  Improve this description with more details about the identified objects and their relationships.
  {{else}}
  Write a detailed description of the scene, focusing on the identified objects and their relationships.
  {{/if}}

  Consider details such as colors, sizes, positions, and any interactions between the objects.
  The description should be vivid and paint a clear picture for someone who cannot see the image.
  Be concise, but do not leave out important details.
  Do not make up facts or hallucinate.
  Only talk about information that can be derived from the image or objects.
  Do not reference the fact that this is a photo or that objects were detected.
  Do not number the points. Do not use bullet points or any list formatting.
  Make sure the response is one single paragraph.

  Return the enhanced scene description:
  `,
});

const enhanceSceneDescriptionFlow = ai.defineFlow(
  {
    name: 'enhanceSceneDescriptionFlow',
    inputSchema: EnhanceSceneDescriptionInputSchema,
    outputSchema: EnhanceSceneDescriptionOutputSchema,
  },
  async input => {
    const {output} = await sceneEnhancementPrompt(input);
    return output!;
  }
);
